name:                echotrainbot
version:             0.1.0.0
github:              "githubuser/echotrainbot"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/marsoig/echotrainbot#readme>

dependencies:
- base >= 4.7 && < 5
- http-conduit >= 2.3.7.3
- aeson == 1.4.7.1
- bytestring == 0.10.10.0
- text >= 1.2.4.0
- transformers == 0.5.6.2
- hslogger==1.3.1.0
- config-parser==1.2.0.0


library:
  source-dirs: src

executables:
  echotrainbot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - echotrainbot

tests:
  echotrainbot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - echotrainbot
